//! 빌드 타임 구문 강조.
//!
//! **인라인 `style=`을 쓰지 않는다.** syntect의 편의 함수(`highlighted_html_for_string`)는
//! 색을 HTML에 직접 박는데, 그러면 테마 하나가 문서에 영구히 고정되어 다크 모드가
//! 불가능해지고, 페이지마다 색 문자열이 중복되며, CSP의 `style-src` 강화도 막힌다.
//! 대신 의미론적 CSS 클래스를 뽑고 테마는 스타일시트로 분리한다 — 그래서 같은 HTML이
//! 라이트/다크 양쪽에서 동작한다.

use crate::config::Highlight as HighlightConfig;
use anyhow::{Context, Result};
use comrak::adapters::SyntaxHighlighterAdapter;
use std::borrow::Cow;
use std::collections::HashMap;
use std::fmt;
use syntect::highlighting::ThemeSet;
use syntect::html::{ClassStyle, ClassedHTMLGenerator, css_for_theme_with_class_style};
use syntect::parsing::SyntaxSet;
use syntect::util::LinesWithEndings;

/// 클래스 접두사. 접두사가 없으면 syntect가 `source`, `keyword`, `string` 같은
/// 일반적인 단어를 그대로 클래스로 쓰기 때문에 사이트 CSS와 충돌한다.
/// syntect API가 `&'static str`을 요구하므로 상수여야 한다.
const CLASS_PREFIX: &str = "hl-";
const CLASS_STYLE: ClassStyle = ClassStyle::SpacedPrefixed {
    prefix: CLASS_PREFIX,
};

pub struct Highlighter {
    syntaxes: SyntaxSet,
}

impl Highlighter {
    pub fn new() -> Self {
        // `extra_newlines` 여야 한다. ClassedHTMLGenerator는 줄 끝의 개행을 요구하고,
        // no-newlines 덤프와 섞으면 조용히 잘못된 결과가 나온다.
        Self {
            syntaxes: two_face::syntax::extra_newlines(),
        }
    }
}

impl Default for Highlighter {
    fn default() -> Self {
        Self::new()
    }
}

impl SyntaxHighlighterAdapter for Highlighter {
    fn write_highlighted(
        &self,
        out: &mut dyn fmt::Write,
        lang: Option<&str>,
        code: &str,
    ) -> fmt::Result {
        let syntax = lang
            .and_then(|l| {
                let l = l.trim();
                self.syntaxes
                    .find_syntax_by_token(l)
                    .or_else(|| self.syntaxes.find_syntax_by_extension(l))
            })
            .unwrap_or_else(|| self.syntaxes.find_syntax_plain_text());

        let mut generator =
            ClassedHTMLGenerator::new_with_class_style(syntax, &self.syntaxes, CLASS_STYLE);
        for line in LinesWithEndings::from(code) {
            // 강조에 실패해도 문서 빌드를 통째로 죽이지 않는다. 이 줄만 포기하고
            // 이스케이프된 원문을 내보낸다.
            if generator
                .parse_html_for_line_which_includes_newline(line)
                .is_err()
            {
                return write_plain(out, code);
            }
        }
        out.write_str(&generator.finalize())
    }

    fn write_pre_tag(
        &self,
        out: &mut dyn fmt::Write,
        _attributes: HashMap<&'static str, Cow<'_, str>>,
    ) -> fmt::Result {
        out.write_str("<pre class=\"highlight\">")
    }

    fn write_code_tag(
        &self,
        out: &mut dyn fmt::Write,
        attributes: HashMap<&'static str, Cow<'_, str>>,
    ) -> fmt::Result {
        // comrak이 `class="language-rust"`를 넘겨준다. 언어를 data 속성으로도 복제해
        // 복사 버튼이나 라벨이 클래스 문자열을 파싱하지 않아도 되게 한다.
        let class = attributes.get("class").map(|c| c.as_ref()).unwrap_or("");
        let lang = class.strip_prefix("language-").unwrap_or("");
        if lang.is_empty() {
            out.write_str("<code>")
        } else {
            write!(
                out,
                "<code class=\"{}\" data-lang=\"{}\">",
                escape_attr(class),
                escape_attr(lang)
            )
        }
    }
}

fn write_plain(out: &mut dyn fmt::Write, code: &str) -> fmt::Result {
    for ch in code.chars() {
        match ch {
            '&' => out.write_str("&amp;")?,
            '<' => out.write_str("&lt;")?,
            '>' => out.write_str("&gt;")?,
            _ => out.write_char(ch)?,
        }
    }
    Ok(())
}

fn escape_attr(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
}

/// 라이트/다크 두 테마의 CSS를 하나의 스타일시트로 합친다.
///
/// 다크 규칙을 두 번 내보낸다: OS 설정을 따르는 `prefers-color-scheme` 안에 한 번,
/// 수동 토글용 `[data-theme="dark"]`에 한 번. 네이티브 CSS 중첩을 써서 생성된
/// 규칙을 문자열로 파싱하지 않고 그대로 감싼다.
pub fn stylesheet(cfg: &HighlightConfig) -> Result<String> {
    let themes = ThemeSet::load_defaults();

    let get = |name: &str| -> Result<String> {
        let theme = themes.themes.get(name).with_context(|| {
            format!(
                "'{name}' 테마를 찾을 수 없습니다. 사용 가능: {}",
                themes.themes.keys().cloned().collect::<Vec<_>>().join(", ")
            )
        })?;
        css_for_theme_with_class_style(theme, CLASS_STYLE)
            .with_context(|| format!("'{name}' 테마의 CSS 생성 실패"))
    };

    let light = get(&cfg.theme_light)?;
    let dark = get(&cfg.theme_dark)?;

    Ok(format!(
        "/* generated by sqzass — do not edit */\n\
         /* light: {} */\n{}\n\
         /* dark: {} */\n\
         @media (prefers-color-scheme: dark) {{\n  :root:not([data-theme=\"light\"]) {{\n{}\n  }}\n}}\n\
         :root[data-theme=\"dark\"] {{\n{}\n}}\n",
        cfg.theme_light, light, cfg.theme_dark, dark, dark
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::Markdown as MarkdownConfig;
    use crate::markdown::Renderer;

    fn render(md: &str) -> String {
        Renderer::new(&MarkdownConfig::default())
            .with_highlighter(Highlighter::new())
            .render(md)
            .html
    }

    #[test]
    fn emits_css_classes_not_inline_styles() {
        let html = render("```rust\nfn main() { let x = 1; }\n```");
        assert!(
            !html.contains("style=\""),
            "인라인 style이 나왔다 — 다크모드가 불가능해진다: {html}"
        );
        assert!(html.contains("hl-"), "하이라이트 클래스가 없다: {html}");
    }

    #[test]
    fn tags_carry_language_metadata() {
        let html = render("```rust\nfn main() {}\n```");
        assert!(html.contains(r#"class="highlight""#), "실제: {html}");
        assert!(html.contains(r#"data-lang="rust""#), "실제: {html}");
    }

    #[test]
    fn unknown_language_falls_back_to_plain_text() {
        let html = render("```notalanguage\nhello\n```");
        assert!(html.contains("hello"), "본문이 사라졌다: {html}");
    }

    #[test]
    fn fence_without_language_still_renders() {
        let html = render("```\nplain code\n```");
        assert!(html.contains("plain code"), "실제: {html}");
    }

    #[test]
    fn code_is_escaped_not_executed() {
        let html = render("```html\n<script>alert(1)</script>\n```");
        assert!(
            !html.contains("<script>alert"),
            "코드 블록 안의 스크립트가 이스케이프되지 않았다: {html}"
        );
    }

    #[test]
    fn two_face_provides_syntaxes_syntect_lacks() {
        // two-face를 넣은 이유가 이것이다 — 개발 도구 문서에 반드시 필요한 언어들이
        // syntect 기본 세트에 없다.
        let h = Highlighter::new();
        for lang in ["toml", "typescript", "dockerfile"] {
            assert!(
                h.syntaxes.find_syntax_by_token(lang).is_some(),
                "'{lang}' 문법이 없다"
            );
        }
    }

    #[test]
    fn stylesheet_contains_both_themes_and_a_manual_toggle() {
        let css = stylesheet(&HighlightConfig::default()).unwrap();
        assert!(
            css.contains("prefers-color-scheme: dark"),
            "OS 다크 대응이 없다"
        );
        assert!(css.contains("[data-theme=\"dark\"]"), "수동 토글 훅이 없다");
        assert!(css.contains(".hl-"), "접두사 붙은 클래스가 없다");
    }

    #[test]
    fn stylesheet_reports_unknown_theme_names() {
        let mut cfg = HighlightConfig::default();
        cfg.theme_dark = "NoSuchTheme".into();
        let err = stylesheet(&cfg).unwrap_err().to_string();
        assert!(err.contains("NoSuchTheme"), "실제: {err}");
    }
}
